#!/bin/sh
set -e

if test "$1" = remove || test "$1" = purge; then
    rm -f \
        /usr/share/icons/OBLinux-Horizon/icon-theme.cache \
        /usr/share/icons/OBLinux-Horizon-Dark/icon-theme.cache
    if command -v glib-compile-schemas >/dev/null 2>&1; then
        glib-compile-schemas /usr/share/glib-2.0/schemas || true
    fi
fi

exit 0
