#!/bin/sh

set -eu

lb config noauto \
	--mode debian \
	--distribution trixie \
	--architecture amd64 \
	--binary-image iso-hybrid \
	--image-name oblinux-debian-gnome \
	--archive-areas "main contrib non-free non-free-firmware" \
	--apt-recommends true \
	--apt-secure true \
	--apt-source-archives true \
	--backports false \
	--security true \
	--updates true \
	--debian-installer none \
	--firmware-binary true \
	--firmware-chroot true \
	--bootloaders "grub-efi grub-pc" \
	--bootappend-live "boot=live components username=live hostname=oblinux-live locales=en_US.UTF-8 keyboard-layouts=us" \
	--checksums sha256 \
	--chroot-filesystem squashfs \
	--chroot-squashfs-compression-type xz \
	--uefi-secure-boot auto \
	--iso-application "OBLinux Debian GNOME Live" \
	--iso-publisher "OBLinux Project" \
	--iso-volume "OBLINUX_LIVE" \
	"${@}"
